[build]
  command = "npm run build"
  publish = "web-build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"
  # GEMINI_API_KEY should be set in Netlify dashboard under Site settings > Environment variables

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
